[package]
name = "aoc-2016-12-17"
version = "0.1.0"
authors = ["Jake Scaife <jakescaife@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
